begin;

with genome_updates as (
  select *
  from (values
    ('BIM Modelling Trainee',
      '["civil engineering","digital construction","bim coordination","revit modelling"]'::jsonb,
      '["3D building modelling","construction drawings","civil structures","coordination between architecture and structure"]'::jsonb,
      '["spatial coordination","clash detection","model-based construction documentation","drawing interpretation"]'::jsonb,
      '["detail-oriented drafting","visual modelling","coordination with design teams","standards-based documentation"]'::jsonb,
      '["BIM studio","construction design office","project coordination environment"]'::jsonb,
      '["Revit model with levels and grids","Navisworks clash report","AutoCAD civil drawing set","BIM coordination screenshots"]'::jsonb,
      '["Autodesk Revit","Navisworks","AutoCAD","Clash Detection","3D Spatial Coordination"]'::jsonb,
      '["dislikes detailed drafting","avoids construction drawings","not comfortable with 3D modelling","prefers no documentation work"]'::jsonb,
      '["Junior Site Engineer"]'::jsonb,
      3, 72),
    ('CAD Design Engineer',
      '["mechanical engineering","mechanical design","parametric modelling","machine components"]'::jsonb,
      '["machine design","3D CAD modelling","assembly design","manufacturing drawings"]'::jsonb,
      '["mechanical design and modelling","tolerance decisions","material and manufacturability tradeoffs"]'::jsonb,
      '["design office work","iterative modelling","precision drafting","review-driven engineering"]'::jsonb,
      '["mechanical design studio","product engineering office"]'::jsonb,
      '["SolidWorks or Creo assembly","GD&T drawing sheet","material selection note","manufacturing-ready CAD model"]'::jsonb,
      '["SolidWorks / Creo","GD&T","Material Selection","Assembly Modeling","Drafting Standards"]'::jsonb,
      '["dislikes CAD modelling","avoids detailed drawings","not interested in mechanical components","prefers no design iteration"]'::jsonb,
      '["FEA / CFD Simulation Trainee","Graduate Engineer Trainee","HVAC Design Engineer"]'::jsonb,
      3, 78),
    ('Data Analyst',
      '["computer science engineering","analytics","business data","dashboarding"]'::jsonb,
      '["data analysis","dashboards","SQL queries","business insights","statistics"]'::jsonb,
      '["analysis and pattern discovery","metric investigation","data cleaning","insight communication"]'::jsonb,
      '["analytical desk work","stakeholder communication","iterative investigation","structured reporting"]'::jsonb,
      '["analytics team","business intelligence function","software product team"]'::jsonb,
      '["SQL analysis notebook","Power BI or Tableau dashboard","Python pandas analysis","Excel model with conclusions"]'::jsonb,
      '["SQL & Query Tuning","Python & Pandas","Power BI / Tableau","Statistics","Excel"]'::jsonb,
      '["dislikes data cleaning","avoids numbers and statistics","not interested in dashboards","prefers no business reporting"]'::jsonb,
      '["Junior Data Engineer","Junior ML Engineer","Prompt Engineer / LLM Support"]'::jsonb,
      4, 82),
    ('Electrical Systems Design Trainee',
      '["electrical engineering","power engineering","building electrical systems","distribution design"]'::jsonb,
      '["power systems","electrical layouts","single line diagrams","load calculations"]'::jsonb,
      '["electrical system sizing","safety and standards compliance","distribution planning","drawing-based design"]'::jsonb,
      '["design office work","calculation-heavy engineering","standards-based review","coordination with site teams"]'::jsonb,
      '["electrical design office","building services project team"]'::jsonb,
      '["AutoCAD Electrical drawing","SLD with load schedule","transformer sizing calculation","wiring layout"]'::jsonb,
      '["AutoCAD Electrical","Single Line Diagrams (SLD)","Load Calculations","Transformer Sizing"]'::jsonb,
      '["dislikes electrical calculations","avoids drawings and standards","not comfortable with power systems","prefers no safety compliance work"]'::jsonb,
      '["PLC / SCADA Automation Trainee","HVAC Design Engineer"]'::jsonb,
      3, 76),
    ('Embedded Systems Engineer Trainee',
      '["electronics and communication engineering","embedded systems","firmware","microcontrollers"]'::jsonb,
      '["microcontrollers","firmware debugging","IoT devices","low-level programming"]'::jsonb,
      '["hardware-software debugging","sensor interfacing","real-time constraints","device bring-up"]'::jsonb,
      '["lab debugging","hands-on prototyping","systematic troubleshooting","code and hardware iteration"]'::jsonb,
      '["electronics lab","embedded product team","firmware development environment"]'::jsonb,
      '["working STM32 or ESP32 prototype","Embedded C firmware repository","FreeRTOS task demo","I2C SPI UART debugging notes"]'::jsonb,
      '["Embedded C","STM32 / ESP32","FreeRTOS","I2C/SPI/UART Protocols","GDB Debugging"]'::jsonb,
      '["dislikes low-level debugging","avoids hardware labs","not interested in C programming","prefers no device testing"]'::jsonb,
      '["Junior Hardware Engineer","PCB Design Engineer Trainee","Robotics Software Engineer Trainee","VLSI Design Trainee"]'::jsonb,
      4, 78),
    ('FEA / CFD Simulation Trainee',
      '["mechanical engineering","simulation engineering","finite element analysis","computational fluid dynamics"]'::jsonb,
      '["simulation","stress analysis","thermal analysis","fluid mechanics","meshing"]'::jsonb,
      '["analysis under stress heat flow and vibration","model validation","boundary condition selection","simulation interpretation"]'::jsonb,
      '["analytical desk work","calculation-heavy engineering","patient model iteration","evidence-based reporting"]'::jsonb,
      '["simulation lab","mechanical analysis team","CAE engineering office"]'::jsonb,
      '["Ansys or Abaqus simulation report","meshed component model","stress or heat transfer study","CFD result with interpretation"]'::jsonb,
      '["Ansys / Abaqus","Fluid Mechanics","Stress Analysis","Meshing","Heat Transfer"]'::jsonb,
      '["dislikes calculations","avoids simulation tools","not interested in physics analysis","prefers no report interpretation"]'::jsonb,
      '["CAD Design Engineer","HVAC Design Engineer","Graduate Engineer Trainee"]'::jsonb,
      4, 76),
    ('Frontend Engineer',
      '["computer science engineering","web engineering","frontend development","react applications"]'::jsonb,
      '["user interfaces","React","responsive layouts","web performance","design implementation"]'::jsonb,
      '["building user interfaces","debugging browser behavior","performance optimization","product flow implementation"]'::jsonb,
      '["product engineering","visual attention to detail","fast iteration","collaboration with design and backend teams"]'::jsonb,
      '["software product team","frontend engineering team","startup or SaaS environment"]'::jsonb,
      '["deployed React app","responsive UI screenshots","TypeScript component code","performance optimization note"]'::jsonb,
      '["HTML/CSS/JS","React","TypeScript","Tailwind","Performance Optimization"]'::jsonb,
      '["dislikes coding","avoids UI details","not interested in browser debugging","prefers no frequent iteration"]'::jsonb,
      '["Full Stack Developer (Junior)","RPA Developer","Prompt Engineer / LLM Support"]'::jsonb,
      5, 82),
    ('Full Stack Developer (Junior)',
      '["computer science engineering","software engineering","web applications","apis and databases"]'::jsonb,
      '["full stack web apps","React","backend APIs","databases","deployment"]'::jsonb,
      '["building and debugging systems","API integration","database modelling","end-to-end feature delivery"]'::jsonb,
      '["product engineering","ownership of features","debugging across layers","test and review discipline"]'::jsonb,
      '["software product team","web application startup","engineering delivery environment"]'::jsonb,
      '["deployed full stack app","REST API with database","React TypeScript repository","PostgreSQL schema and queries"]'::jsonb,
      '["React & TypeScript","Node.js / Express","PostgreSQL / SQL","Tailwind CSS","REST APIs"]'::jsonb,
      '["dislikes coding","avoids backend debugging","not interested in databases","prefers no production ownership"]'::jsonb,
      '["Frontend Engineer","Junior Data Engineer","RPA Developer","Prompt Engineer / LLM Support"]'::jsonb,
      6, 84),
    ('Game Developer',
      '["computer science engineering","interactive media","game programming","real-time graphics"]'::jsonb,
      '["gameplay programming","2D and 3D games","Unity","Unreal","physics simulation"]'::jsonb,
      '["game mechanics implementation","real-time rendering","physics tuning","player interaction debugging"]'::jsonb,
      '["creative coding","iterative prototyping","performance-minded debugging","visual problem solving"]'::jsonb,
      '["game studio","interactive media team","indie game project environment"]'::jsonb,
      '["playable Unity or Unreal prototype","game mechanic demo","physics or shader implementation","C# or C++ gameplay code"]'::jsonb,
      '["Unity / C#","Unreal / C++","Mathematics & 3D Vector Math","Physics Engines"]'::jsonb,
      '["dislikes games","avoids graphics math","not interested in visual prototyping","prefers no real-time debugging"]'::jsonb,
      '["Frontend Engineer","Robotics Software Engineer Trainee","Full Stack Developer (Junior)"]'::jsonb,
      7, 70),
    ('Graduate Engineer Trainee',
      '["mechanical engineering","manufacturing operations","plant engineering","quality control"]'::jsonb,
      '["plant operations","manufacturing processes","quality audits","production line management"]'::jsonb,
      '["field execution and process improvement","root-cause analysis","quality checks","shop-floor coordination"]'::jsonb,
      '["operations and coordination","hands-on plant work","process discipline","safety-aware execution"]'::jsonb,
      '["manufacturing plant","production floor","quality engineering environment"]'::jsonb,
      '["manufacturing internship proof","quality checklist","process improvement note","engineering drawing interpretation"]'::jsonb,
      '["Engineering Drawing","Manufacturing Processes","GD&T","Quality Audits","Safety Protocols"]'::jsonb,
      '["dislikes shop-floor work","avoids manufacturing operations","not comfortable with safety protocols","prefers no field coordination"]'::jsonb,
      '["CAD Design Engineer","FEA / CFD Simulation Trainee","HVAC Design Engineer"]'::jsonb,
      3, 78),
    ('HVAC Design Engineer',
      '["mechanical engineering","building services","hvac design","thermal systems"]'::jsonb,
      '["HVAC systems","thermal comfort","duct and piping layouts","commercial building services"]'::jsonb,
      '["heat load calculation","energy system design","layout coordination","equipment sizing"]'::jsonb,
      '["design office work","calculation-heavy engineering","coordination with architects and site teams","standards-based documentation"]'::jsonb,
      '["building services design office","MEP project team","commercial facilities engineering"]'::jsonb,
      '["heat load calculation sheet","AutoCAD HVAC layout","duct design drawing","piping layout"]'::jsonb,
      '["Thermodynamics","AutoCAD","Heat Load Calculations","Piping Layout","Duct Design"]'::jsonb,
      '["dislikes thermal calculations","avoids building services drawings","not interested in HVAC systems","prefers no coordination with site teams"]'::jsonb,
      '["CAD Design Engineer","FEA / CFD Simulation Trainee","Electrical Systems Design Trainee"]'::jsonb,
      4, 78),
    ('Junior Data Engineer',
      '["computer science engineering","data infrastructure","etl pipelines","data warehousing"]'::jsonb,
      '["data pipelines","SQL","Python","ETL","cloud storage","data reliability"]'::jsonb,
      '["pipeline construction","data quality debugging","batch workflow orchestration","warehouse modelling"]'::jsonb,
      '["backend-oriented engineering","systematic debugging","reliability focus","collaboration with analytics teams"]'::jsonb,
      '["data platform team","software engineering environment","analytics infrastructure team"]'::jsonb,
      '["ETL pipeline project","Airflow DAG","PostgreSQL data model","Python or PySpark processing job"]'::jsonb,
      '["SQL","Python / PySpark","Airflow","PostgreSQL","Cloud Storage"]'::jsonb,
      '["dislikes backend data work","avoids SQL","not interested in pipelines","prefers no reliability debugging"]'::jsonb,
      '["Data Analyst","Full Stack Developer (Junior)","Junior ML Engineer"]'::jsonb,
      5, 82),
    ('Junior Hardware Engineer',
      '["electronics and communication engineering","electronics hardware","schematic capture","pcb validation"]'::jsonb,
      '["digital electronics","schematics","PCB prototypes","lab instruments","microcontrollers"]'::jsonb,
      '["circuit validation","hardware debugging","prototype bring-up","component-level troubleshooting"]'::jsonb,
      '["lab debugging","hands-on electronics","careful measurement","iterative prototype validation"]'::jsonb,
      '["electronics lab","hardware validation bench","prototype engineering team"]'::jsonb,
      '["schematic capture project","oscilloscope debugging log","microcontroller board validation","digital electronics prototype"]'::jsonb,
      '["Schematic Capture","Microcontrollers","C/C++","Oscilloscopes","Digital Electronics"]'::jsonb,
      '["dislikes circuits","avoids lab instruments","not interested in electronics hardware","prefers no prototype debugging"]'::jsonb,
      '["Embedded Systems Engineer Trainee","PCB Design Engineer Trainee","VLSI Design Trainee"]'::jsonb,
      3, 74),
    ('Junior ML Engineer',
      '["computer science engineering","ai and data science","machine learning","model deployment"]'::jsonb,
      '["machine learning","Python","model training","LLMs","deployment"]'::jsonb,
      '["model evaluation","feature experimentation","prediction quality improvement","ML API deployment"]'::jsonb,
      '["analytical engineering","experiment tracking","research-to-code implementation","debugging model behavior"]'::jsonb,
      '["AI product team","data science team","ML engineering environment"]'::jsonb,
      '["trained ML model notebook","PyTorch or TensorFlow project","FastAPI model API","evaluation metrics report"]'::jsonb,
      '["Python","PyTorch / TensorFlow","Scikit-Learn","FastAPI","Docker","Git"]'::jsonb,
      '["dislikes math and statistics","avoids model debugging","not interested in Python","prefers no experimentation"]'::jsonb,
      '["Data Analyst","Junior Data Engineer","Prompt Engineer / LLM Support"]'::jsonb,
      6, 84),
    ('Junior Site Engineer',
      '["civil engineering","construction management","site supervision","quality and safety"]'::jsonb,
      '["construction sites","site supervision","surveying","concrete work","contractor coordination"]'::jsonb,
      '["field execution","daily site coordination","quality checks","safety compliance","measurement verification"]'::jsonb,
      '["field work","people coordination","practical problem solving","documentation of site progress"]'::jsonb,
      '["construction site","civil project field team","contractor coordination environment"]'::jsonb,
      '["site internship diary","surveying record","bar bending schedule","concrete quality checklist"]'::jsonb,
      '["Site Supervision","Concrete Technology","Bar Bending Schedules","Surveying","Safety Standards"]'::jsonb,
      '["dislikes outdoor site work","avoids contractor coordination","not comfortable with safety checks","prefers desk-only design work"]'::jsonb,
      '["BIM Modelling Trainee"]'::jsonb,
      3, 76),
    ('PCB Design Engineer Trainee',
      '["electronics and communication engineering","electronics packaging","pcb layout","signal integrity"]'::jsonb,
      '["PCB layout","electronics design","component selection","fabrication outputs","signal integrity"]'::jsonb,
      '["board layout constraints","EMC and signal integrity tradeoffs","component placement","fabrication readiness"]'::jsonb,
      '["detail-oriented design","lab-aware validation","design review discipline","iterative layout correction"]'::jsonb,
      '["electronics design lab","PCB design office","hardware product team"]'::jsonb,
      '["KiCAD or Altium board file","fabrication Gerbers","component selection rationale","signal integrity checklist"]'::jsonb,
      '["KiCAD / Altium Designer","Signal Integrity","Component Selection","EMC Compliance"]'::jsonb,
      '["dislikes PCB layout","avoids component-level detail","not interested in electronics fabrication","prefers no design rule checking"]'::jsonb,
      '["Junior Hardware Engineer","Embedded Systems Engineer Trainee","VLSI Design Trainee"]'::jsonb,
      4, 76),
    ('PLC / SCADA Automation Trainee',
      '["electrical engineering","industrial automation","plc programming","scada systems"]'::jsonb,
      '["industrial automation","PLC programming","SCADA HMI","manufacturing assembly lines","sensors"]'::jsonb,
      '["control sequence design","factory automation debugging","sensor integration","operator interface setup"]'::jsonb,
      '["hands-on automation","field and panel work","logic-based troubleshooting","coordination with maintenance teams"]'::jsonb,
      '["industrial plant","automation lab","factory commissioning environment"]'::jsonb,
      '["ladder logic program","SCADA HMI screen","PLC sensor integration demo","automation panel wiring note"]'::jsonb,
      '["Ladder Logic","Siemens / Allen Bradley PLCs","SCADA HMI","Industrial Sensors"]'::jsonb,
      '["dislikes factory environments","avoids control wiring","not interested in ladder logic","prefers no commissioning work"]'::jsonb,
      '["Electrical Systems Design Trainee","Robotics Software Engineer Trainee","Embedded Systems Engineer Trainee"]'::jsonb,
      4, 78),
    ('Prompt Engineer / LLM Support',
      '["computer science engineering","ai applications","llm evaluation","enterprise workflow automation"]'::jsonb,
      '["LLM apps","prompt design","AI agents","evaluation benchmarks","JSON APIs"]'::jsonb,
      '["prompt optimization","LLM output evaluation","workflow automation","AI agent debugging"]'::jsonb,
      '["analytical writing","structured experimentation","support-oriented debugging","documentation-heavy iteration"]'::jsonb,
      '["AI application team","enterprise support workflow","software product environment"]'::jsonb,
      '["prompt evaluation matrix","LangChain or LlamaIndex prototype","JSON API integration","LLM output benchmark report"]'::jsonb,
      '["Prompt Design","Python","LangChain / LlamaIndex","Eval Benchmarks","JSON API"]'::jsonb,
      '["dislikes writing and evaluation","avoids ambiguous AI outputs","not interested in prompt testing","prefers no support workflows"]'::jsonb,
      '["Junior ML Engineer","Full Stack Developer (Junior)","Data Analyst"]'::jsonb,
      5, 80),
    ('RF / Telecom Engineer Trainee',
      '["electronics and communication engineering","telecommunications","rf systems","wireless networks"]'::jsonb,
      '["5G networks","RF circuits","antenna design","wireless propagation","spectrum analysis"]'::jsonb,
      '["signal propagation analysis","network optimization","RF measurement","antenna and circuit tuning"]'::jsonb,
      '["lab and field testing","measurement-driven analysis","standards-aware engineering","patient troubleshooting"]'::jsonb,
      '["telecom lab","wireless network field team","RF testing environment"]'::jsonb,
      '["RF circuit measurement","spectrum analyzer screenshots","antenna design note","5G or LTE protocol study"]'::jsonb,
      '["5G/LTE Protocols","RF Circuits","Spectrum Analyzers","Antenna Design"]'::jsonb,
      '["dislikes signals and networks","avoids RF lab equipment","not interested in telecom standards","prefers no field measurement"]'::jsonb,
      '["Junior Hardware Engineer","Embedded Systems Engineer Trainee","VLSI Design Trainee"]'::jsonb,
      4, 74),
    ('Robotics Software Engineer Trainee',
      '["robotics and automation engineering","robotics software","autonomous navigation","computer vision"]'::jsonb,
      '["robots","ROS","path planning","SLAM","computer vision","simulation"]'::jsonb,
      '["robot navigation","kinematics and perception integration","simulation-to-hardware debugging","autonomy algorithms"]'::jsonb,
      '["hands-on software debugging","math-heavy implementation","lab prototyping","iterative simulation testing"]'::jsonb,
      '["robotics lab","automation engineering team","simulation and prototype environment"]'::jsonb,
      '["ROS or ROS2 robot project","Gazebo simulation","SLAM or path planning demo","OpenCV perception prototype"]'::jsonb,
      '["ROS / ROS2","C++ / Python","SLAM & Path Planning","Gazebo Simulation","OpenCV"]'::jsonb,
      '["dislikes robotics labs","avoids math-heavy coding","not interested in simulation debugging","prefers no hardware-software integration"]'::jsonb,
      '["Embedded Systems Engineer Trainee","PLC / SCADA Automation Trainee","Game Developer","Junior ML Engineer"]'::jsonb,
      6, 78),
    ('RPA Developer',
      '["computer science engineering","automation","business process automation","workflow scripting"]'::jsonb,
      '["workflow automation","UiPath","process mapping","Python scripting","SQL"]'::jsonb,
      '["manual workflow elimination","process mapping","bot exception handling","business rule automation"]'::jsonb,
      '["operations-facing engineering","structured process thinking","low-code and scripting mix","stakeholder communication"]'::jsonb,
      '["business automation team","enterprise operations environment","software support team"]'::jsonb,
      '["UiPath or Automation Anywhere bot","process map","Python automation script","SQL-backed workflow demo"]'::jsonb,
      '["UiPath / Automation Anywhere","Python Scripting","SQL","Process Mapping"]'::jsonb,
      '["dislikes repetitive business processes","avoids stakeholder requirement gathering","not interested in automation tools","prefers pure coding only"]'::jsonb,
      '["Full Stack Developer (Junior)","Frontend Engineer","Data Analyst"]'::jsonb,
      4, 76),
    ('SOC Analyst L1',
      '["computer science engineering","cybersecurity","security operations","incident monitoring"]'::jsonb,
      '["cybersecurity","network security","SIEM monitoring","incident response","Linux"]'::jsonb,
      '["threat triage","log analysis","incident escalation","network traffic investigation"]'::jsonb,
      '["alert-driven analysis","shift-based monitoring","calm incident response","detail-oriented investigation"]'::jsonb,
      '["security operations center","enterprise security team","monitoring and response environment"]'::jsonb,
      '["SIEM alert triage report","Wireshark packet analysis","Linux security lab","incident response playbook exercise"]'::jsonb,
      '["Network Security","Linux","SIEM Tools","Wireshark","Incident Response"]'::jsonb,
      '["dislikes monitoring alerts","avoids cybersecurity topics","not comfortable with Linux","prefers no shift-based operations"]'::jsonb,
      '["Full Stack Developer (Junior)","Junior Data Engineer","Prompt Engineer / LLM Support"]'::jsonb,
      5, 80),
    ('VLSI Design Trainee',
      '["electronics and communication engineering","semiconductor","rtl design","digital logic"]'::jsonb,
      '["chip design","RTL","Verilog","FPGA","timing analysis","digital circuits"]'::jsonb,
      '["digital logic implementation","RTL verification","timing closure basics","FPGA prototyping"]'::jsonb,
      '["detail-oriented design","simulation-first debugging","hardware logic reasoning","patient verification"]'::jsonb,
      '["semiconductor design team","electronics lab","RTL simulation environment"]'::jsonb,
      '["Verilog module with testbench","FPGA prototype","RTL simulation waveform","static timing analysis exercise"]'::jsonb,
      '["Verilog / SystemVerilog","RTL Design","Digital Logic","FPGA Prototyping","Static Timing Analysis"]'::jsonb,
      '["dislikes digital logic","avoids Verilog coding","not interested in chip design","prefers no simulation and verification"]'::jsonb,
      '["Junior Hardware Engineer","PCB Design Engineer Trainee","Embedded Systems Engineer Trainee"]'::jsonb,
      5, 78)
  ) as v(title, domains, preferred_interests, problem_types, work_styles, environments, preferred_evidence, prerequisites, anti_signals, adjacent_titles, transition_difficulty, market_demand_score)
),
resolved_updates as (
  select
    r.id as role_id,
    u.domains,
    u.preferred_interests,
    u.problem_types,
    u.work_styles,
    u.environments,
    u.preferred_evidence,
    u.prerequisites,
    u.anti_signals,
    coalesce(jsonb_agg(adj.id order by adj.title) filter (where adj.id is not null), '[]'::jsonb) as adjacent_role_ids,
    u.transition_difficulty,
    u.market_demand_score
  from genome_updates u
  join public.career_roles r on r.title = u.title and r.status = 'published'
  left join lateral jsonb_array_elements_text(u.adjacent_titles) adjacent_title(title) on true
  left join public.career_roles adj on adj.title = adjacent_title.title and adj.status = 'published'
  group by r.id, u.domains, u.preferred_interests, u.problem_types, u.work_styles, u.environments, u.preferred_evidence, u.prerequisites, u.anti_signals, u.transition_difficulty, u.market_demand_score
)
update public.career_role_genomes g
set domains = u.domains,
    preferred_interests = u.preferred_interests,
    problem_types = u.problem_types,
    work_styles = u.work_styles,
    environments = u.environments,
    preferred_evidence = u.preferred_evidence,
    prerequisites = u.prerequisites,
    anti_signals = u.anti_signals,
    adjacent_role_ids = u.adjacent_role_ids,
    transition_difficulty = u.transition_difficulty,
    market_demand_score = u.market_demand_score,
    updated_at = now()
from resolved_updates u
where g.role_id = u.role_id
  and g.status = 'published';

do $$
declare
  missing_count integer;
begin
  select count(*)
  into missing_count
  from public.career_roles r
  left join public.career_role_genomes g on g.role_id = r.id and g.status = 'published'
  where r.status = 'published'
    and (
      g.role_id is null
      or jsonb_array_length(g.anti_signals) = 0
      or jsonb_array_length(g.adjacent_role_ids) = 0
      or jsonb_array_length(g.preferred_interests) = 0
      or jsonb_array_length(g.problem_types) = 0
      or jsonb_array_length(g.work_styles) = 0
      or jsonb_array_length(g.environments) = 0
      or jsonb_array_length(g.preferred_evidence) = 0
      or jsonb_array_length(g.prerequisites) = 0
    );

  if missing_count > 0 then
    raise exception 'career_intelligence_v2_genome_intelligence incomplete for % published roles', missing_count;
  end if;
end $$;

commit;
